platform :ios, '9.0'
workspace '../MultiSpecs'

target 'MultiSpecsDemo' do
  use_frameworks!

  pod 'MultiSpecs/Extensions', :path => '../'  

  target 'MultiSpecsDemoTests' do
    inherit! :search_paths
  end

end
